# https://github.com/marketplace/actions/eslint-js-ts-action

- name: ESLint (JS/TS) Action 
  uses: iCrawl/action-eslint@v1

on:
    push:
    pull_request:
  
  jobs:
    eslint:
      name: eslint
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: apps # only if a different glob is needed, default: src